global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'vmagent'
    static_configs:
      - targets: ['vmagent:8429']
  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['victoriametrics:8428']
  - job_name: 'datapool-app'
    static_configs:
      - targets: ['http://192.168.0.5:8084/actuator/prometheus']